### ISSUE TITLE
Consider Apache licence?

### ISSUE THREAD

**Issue by andrewleech** [luckydonald/pony_up#2]
Hello, would you consider changing you licence to be compatible with PonyORM which is using Apache 2.0?

https://docs.ponyorm.com/ : `Starting with the version 0.7, Pony ORM is released under the Apache License, Version 2.0.`

I was about to use your library in a work project and make some contributions back with improvements but just saw it's listed as GPLv3+ in setup.py, meaning I can't use it in our codebase.

Cheers,
Andrew

**Comment by luckydonald** [comment]
Sure, I'm fine with a `Apache License, Version 2.0` for usage in ponyorm, go ahead.

**Comment by luckydonald** [comment]
Whoosie for the late feedback. You could have pinged me in the ponyorm chat about it.
